### ISSUE TITLE
Unable to download prebuilt binaries or complete the full build of skia.

### ISSUE THREAD

**Issue by photex** [rust-skia/rust-skia#254]
When trying to build Skulpin I'm getting the following error (the tarball for the 0.23 release is being incorrectly determined)
```
HOST: x86_64-pc-windows-msvc
TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.23.0/bf61a03a26d021e125fb-x86_64-pc-windows-msvc-svg-textlayout-vulkan-static
  FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.23.0/skia-binaries-bf61a03a26d021e125fb-x86_64-pc-windows-msvc-svg-textlayout-vulkan-static.tar.gz
DOWNLOAD AND INSTALL FAILED: [22] HTTP response code said error
```

When trying to build rust-skia from the repo I get a different error about a missing git ref:
```
--- stderr
Submodule 'skia-bindings/depot_tools' (https://github.com/rust-skia/depot_tools.git) registered for path 'depot_tools'
Submodule 'skia' (https://github.com/google/skia.git) registered for path 'skia'
Cloning into 'C:/projects/rust-skia/skia-bindings/depot_tools'...
Cloning into 'C:/projects/rust-skia/skia-bindings/skia'...
From https://github.com/google/skia
 * branch            2542bdfcd686c7bfa9f687d80627f8ef468b2838 -> FETCH_HEAD
warning: remote HEAD refers to nonexistent ref, unable to checkout.

ninja: fatal: ReadFile: The handle is invalid.
```

I don't know exactly how to work this out as this is the first interaction with the system I've had so far. Any tips?

**Comment by pragmatrix** [comment]
Hello @photex,

the first error is expected, there is no "static" build available for the prebuilt binaries. I am guessing you enabled the "crt-static" target feature [somewhere](https://github.com/rust-lang/rfcs/blob/master/text/1721-crt-static.md).

I can't reproduce the second problem, can you retry that with `cargo build -vv` and post the full log?

**Comment by photex** [comment]
Ah good catch. Yep, I have that set in ~/.cargo/config since I use it for essentially everything to avoid problems when running binaries on some other machines. I wonder if I can selectively disable it. 🤔 

Here is the full output from the skia-bindings crate build:
```
   Compiling skia-bindings v0.24.0 (C:\projects\rust-skia\skia-bindings)
     Running `set CARGO_PKG_VERSION_MAJOR=0&& set CARGO_PKG_VERSION_PATCH=0&& set CARGO_PKG_HOMEPAGE=https://github.com/rust-skia/rust-skia/skia-bindings&& set CARGO_PKG_NAME=skia-bindings&& set CARGO_PKG_VERSION=0.24.0&& set CARGO_PKG_REPOSITORY=https://github.com/rust-skia/rust-skia&& set CARGO_PKG_AUTHORS="LongYinan <lynweklm@gmail.com>:Armin Sander <armin@replicator.org>"&& set CARGO_MANIFEST_DIR=c:\projects\rust-skia\skia-bindings&& set CARGO=\\?\C:\Users\phote\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin\cargo.exe&& set CARGO_PKG_VERSION_MINOR=24&& set CARGO_PKG_VERSION_PRE=&& set PATH="c:\projects\rust-skia\target\release\deps;C:\Users\phote\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin;C:\Users\phote\.cargo\bin;C:\Users\phote\.rustup\toolchains\stable-x86_64-pc-windows-msvc\bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Perforce\;C:\Program Files (x86)\Bitvise SSH Client;C:\SVN\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Users\phote\scoop\apps\nu\current\Plugins;C:\Users\phote\scoop\apps\python\current;C:\Users\phote\scoop\apps\python\current\Scripts;C:\Users\phote\.cargo\bin;C:\Users\phote\scoop\shims;C:\Users\phote\AppData\Local\Microsoft\WindowsApps;C:\Users\phote\scoop\apps\llvm\current\bin"&& set CARGO_PKG_DESCRIPTION="Skia Bindings for Rust"&& rustc --edition=2018 --crate-name build_script_build skia-bindings\build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 --cfg "feature=\"default\"" -C metadata=e0ed5a3c4e0371e3 -C extra-filename=-e0ed5a3c4e0371e3 --out-dir c:\projects\rust-skia\target\release\build\skia-bindings-e0ed5a3c4e0371e3 -C linker=c:/Users/phote/scoop/shims/lld-link.exe -L dependency=c:\projects\rust-skia\target\release\deps --extern bindgen=c:\projects\rust-skia\target\release\deps\libbindgen-cd2786181e931cf3.rlib --extern cc=c:\projects\rust-skia\target\release\deps\libcc-617db97d5eee0f01.rlib --extern curl=c:\projects\rust-skia\target\release\deps\libcurl-0cda84dd74fa532e.rlib --extern flate2=c:\projects\rust-skia\target\release\deps\libflate2-7f00a9c55e625033.rlib --extern heck=c:\projects\rust-skia\target\release\deps\libheck-60d37b316180d7e0.rlib --extern regex=c:\projects\rust-skia\target\release\deps\libregex-017e8043e5e5abef.rlib --extern serde_json=c:\projects\rust-skia\target\release\deps\libserde_json-9726f201a913d65e.rlib --extern tar=c:\projects\rust-skia\target\release\deps\libtar-9704eb6a855cd925.rlib --extern toml=c:\projects\rust-skia\target\release\deps\libtoml-c023069594384f31.rlib -C target-feature=+crt-static -L native=c:\projects\rust-skia\target\release\build\curl-sys-2dfd7209e90bfbba\out\build -L native=c:\projects\rust-skia\target\release\build\libz-sys-4a4c43dd7c1a639f\out\build`
     Running `c:\projects\rust-skia\target\release\build\skia-bindings-e0ed5a3c4e0371e3\build-script-build`
[skia-bindings 0.24.0] cargo:rerun-if-env-changed=SKIA_DEBUG
[skia-bindings 0.24.0] HOST: x86_64-pc-windows-msvc
[skia-bindings 0.24.0] cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
[skia-bindings 0.24.0] cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
[skia-bindings 0.24.0] STARTING A FULL BUILD
[skia-bindings 0.24.0] Probing 'python'
[skia-bindings 0.24.0] Python 2 found: "python"
[skia-bindings 0.24.0] Skipping "../src".
[skia-bindings 0.24.0] skia\buildtools                      @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
[skia-bindings 0.24.0] skia\third_party/externals/libjpe... @ 574f3a772c96dc9db2c98ef24706feb3f6dbda9a
[skia-bindings 0.24.0] skia\third_party/externals/opencl... @ 4e6d30e406d2e5a65e1d65e404fe6df5f772a32b
[skia-bindings 0.24.0] skia\third_party/externals/imgui     @ d38d7c6628bebd02692cfdd6fa76b4d992a35b75
[skia-bindings 0.24.0] skia\common                          @ 9737551d7a52c3db3262db5856e6bcd62c462b92
[skia-bindings 0.24.0] skia\third_party/externals/expat     @ e5aa0a2cb0a5f759ef31c0819dc67d9b14246a4a
[skia-bindings 0.24.0] skia\third_party/externals/freetype  @ 05439f5cc69eaa3deaf3db52a7999af09a2c293a
[skia-bindings 0.24.0] skia\third_party/externals/egl-re... @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
[skia-bindings 0.24.0] skia\third_party/externals/piex      @ bb217acdca1cc0c16b704669dd6f91a1b509c406
[skia-bindings 0.24.0] skia\third_party/externals/microh... @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
[skia-bindings 0.24.0] skia\third_party/externals/libwebp   @ 0fe1a89dbf1930fc2554dbe76adad5d962054ead
[skia-bindings 0.24.0] skia\third_party/externals/dng_sdk   @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
[skia-bindings 0.24.0] skia\third_party/externals/libpng    @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
[skia-bindings 0.24.0] skia\third_party/externals/lua       @ e354c6355e7f48e087678ec49e340ca0696725b1
[skia-bindings 0.24.0] skia\third_party/externals/dawn      @ fd90d767ba58faedc1fa74363ebcb2eb99159ba1
[skia-bindings 0.24.0] skia\third_party/externals/sfntly    @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
[skia-bindings 0.24.0] skia\third_party/externals/spirv-... @ 53ab2144b90abede33be5161aec5dfc94ddc3caf
[skia-bindings 0.24.0] skia\third_party/externals/spirv-... @ 29c11140baaf9f7fdaa39a583672c556bf1795a1
[skia-bindings 0.24.0] skia\third_party/externals/spirv-... @ 0c4feb643b89d1792b02f7cbef315e9d95633bd7
[skia-bindings 0.24.0] skia\third_party/externals/zlib      @ 47af7c547f8551bd25424e56354a2ae1e9062859
[skia-bindings 0.24.0] skia\third_party/externals/harfbuzz  @ 1bada656a86e9cb27d4a6b9fcc50748f0bd9c1d9
[skia-bindings 0.24.0] skia\third_party/externals/angle2    @ ed6e230ec65e7fe4acff17a00eb85bc3c8459bb5
[skia-bindings 0.24.0] skia\third_party/externals/icu       @ 407b39301e71006b68bd38e770f35d32398a7b14
[skia-bindings 0.24.0] skia\third_party/externals/opencl... @ 932ed55c85f887041291cef8019e54280c033c35
[skia-bindings 0.24.0] skia\third_party/externals/wuffs     @ 4080840928c0b05a80cda0d14ac2e2615f679f1a
[skia-bindings 0.24.0] skia\third_party/externals/opengl... @ 14b80ebeab022b2c78f84a573f01028c96075553
[skia-bindings 0.24.0] skia\third_party/externals/sdl       @ 5d7cfcca344034aff9327f77fc181ae3754e7a90
[skia-bindings 0.24.0] skia\third_party/externals/swifts... @ 6652f0b6428777b5a4a3d191cc30d8b31366b999
[skia-bindings 0.24.0] Skia args: is_official_build=true is_debug=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_libwebp=false skia_use_system_zlib=false skia_enable_skottie=false skia_use_xps=false skia_use_dng_sdk=false skia_enable_particles=false cc="clang" cxx="clang++" skia_use_icu=false win_vc="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC" clang_win="C:/Program Files/LLVM" skia_use_expat=false extra_cflags=["/MT"]
[skia-bindings 0.24.0] Done. Made 49 targets from 27 files in 464ms
[skia-bindings 0.24.0] ninja: Entering directory `c:\projects\rust-skia\target\release\build\skia-bindings-2c14e5fbc137d3d7\out\skia'
[skia-bindings 0.24.0] [1/902] compile ../../../../../../skia-bindings/skia/src/opts/SkOpts_avx.cpp
[skia-bindings 0.24.0] FAILED: obj/src/opts/avx.SkOpts_avx.obj
[skia-bindings 0.24.0] "C:/Program Files/LLVM/bin/clang-cl.exe" /nologo /showIncludes /FC -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../../../../../../skia-bindings/skia /arch:AVX /bigobj /utf-8 -fms-compatibility-version=19 -imsvc "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC/Tools/MSVC/14.24.28314/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/winrt" /O2 /Zc:inline -Wno-unused-parameter /MT  /GR- /c ../../../../../../skia-bindings/skia/src/opts/SkOpts_avx.cpp /Foobj/src/opts/avx.SkOpts_avx.obj /Fd"obj/avx_c.pdb"
[skia-bindings 0.24.0] CreateProcess failed: The system cannot find the file specified.
[skia-bindings 0.24.0] ninja: fatal: ReadFile: The handle is invalid.
[skia-bindings 0.24.0]
[skia-bindings 0.24.0] thread 'main' panicked at '`ninja` returned an error, please check the output for details.', skia-bindings\build_support\skia.rs:609:5
[skia-bindings 0.24.0] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: failed to run custom build command for `skia-bindings v0.24.0 (C:\projects\rust-skia\skia-bindings)`

Caused by:
  process didn't exit successfully: `c:\projects\rust-skia\target\release\build\skia-bindings-e0ed5a3c4e0371e3\build-script-build` (exit code: 101)   --- stdout
cargo:rerun-if-env-changed=SKIA_DEBUG
HOST: x86_64-pc-windows-msvc
cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
STARTING A FULL BUILD
Probing 'python'
Python 2 found: "python"
Skipping "../src".
skia\buildtools                      @ 505de88083136eefd056e5ee4ca0f01fe9b33de8
skia\third_party/externals/libjpe... @ 574f3a772c96dc9db2c98ef24706feb3f6dbda9a
skia\third_party/externals/opencl... @ 4e6d30e406d2e5a65e1d65e404fe6df5f772a32b
skia\third_party/externals/imgui     @ d38d7c6628bebd02692cfdd6fa76b4d992a35b75
skia\common                          @ 9737551d7a52c3db3262db5856e6bcd62c462b92
skia\third_party/externals/expat     @ e5aa0a2cb0a5f759ef31c0819dc67d9b14246a4a
skia\third_party/externals/freetype  @ 05439f5cc69eaa3deaf3db52a7999af09a2c293a
skia\third_party/externals/egl-re... @ a0bca08de07c7d7651047bedc0b653cfaaa4f2ae
skia\third_party/externals/piex      @ bb217acdca1cc0c16b704669dd6f91a1b509c406
skia\third_party/externals/microh... @ 748945ec6f1c67b7efc934ab0808e1d32f2fb98d
skia\third_party/externals/libwebp   @ 0fe1a89dbf1930fc2554dbe76adad5d962054ead
skia\third_party/externals/dng_sdk   @ c8d0c9b1d16bfda56f15165d39e0ffa360a11123
skia\third_party/externals/libpng    @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
skia\third_party/externals/lua       @ e354c6355e7f48e087678ec49e340ca0696725b1
skia\third_party/externals/dawn      @ fd90d767ba58faedc1fa74363ebcb2eb99159ba1
skia\third_party/externals/sfntly    @ b55ff303ea2f9e26702b514cf6a3196a2e3e2974
skia\third_party/externals/spirv-... @ 53ab2144b90abede33be5161aec5dfc94ddc3caf
skia\third_party/externals/spirv-... @ 29c11140baaf9f7fdaa39a583672c556bf1795a1
skia\third_party/externals/spirv-... @ 0c4feb643b89d1792b02f7cbef315e9d95633bd7
skia\third_party/externals/zlib      @ 47af7c547f8551bd25424e56354a2ae1e9062859
skia\third_party/externals/harfbuzz  @ 1bada656a86e9cb27d4a6b9fcc50748f0bd9c1d9
skia\third_party/externals/angle2    @ ed6e230ec65e7fe4acff17a00eb85bc3c8459bb5
skia\third_party/externals/icu       @ 407b39301e71006b68bd38e770f35d32398a7b14
skia\third_party/externals/opencl... @ 932ed55c85f887041291cef8019e54280c033c35
skia\third_party/externals/wuffs     @ 4080840928c0b05a80cda0d14ac2e2615f679f1a
skia\third_party/externals/opengl... @ 14b80ebeab022b2c78f84a573f01028c96075553
skia\third_party/externals/sdl       @ 5d7cfcca344034aff9327f77fc181ae3754e7a90
skia\third_party/externals/swifts... @ 6652f0b6428777b5a4a3d191cc30d8b31366b999
Skia args: is_official_build=true is_debug=false skia_use_system_libjpeg_turbo=false skia_use_system_libpng=false skia_use_libwebp=false skia_use_system_zlib=false skia_enable_skottie=false skia_use_xps=false skia_use_dng_sdk=false skia_enable_particles=false cc="clang" cxx="clang++" skia_use_icu=false win_vc="C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC" clang_win="C:/Program Files/LLVM" skia_use_expat=false extra_cflags=["/MT"]
Done. Made 49 targets from 27 files in 464ms
ninja: Entering directory `c:\projects\rust-skia\target\release\build\skia-bindings-2c14e5fbc137d3d7\out\skia'
[1/902] compile ../../../../../../skia-bindings/skia/src/opts/SkOpts_avx.cpp
FAILED: obj/src/opts/avx.SkOpts_avx.obj
"C:/Program Files/LLVM/bin/clang-cl.exe" /nologo /showIncludes /FC -D_CRT_SECURE_NO_WARNINGS -D_HAS_EXCEPTIONS=0 -DWIN32_LEAN_AND_MEAN -DNOMINMAX -DNDEBUG -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../../../../../../skia-bindings/skia /arch:AVX /bigobj /utf-8 -fms-compatibility-version=19 -imsvc "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC/Tools/MSVC/14.24.28314/include" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/shared" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/ucrt" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/um" -imsvc "C:/Program Files (x86)/Windows Kits/10/Include/10.0.18362.0/winrt" /O2 /Zc:inline -Wno-unused-parameter /MT  /GR- /c ../../../../../../skia-bindings/skia/src/opts/SkOpts_avx.cpp /Foobj/src/opts/avx.SkOpts_avx.obj /Fd"obj/avx_c.pdb"
CreateProcess failed: The system cannot find the file specified.

--- stderr
ninja: fatal: ReadFile: The handle is invalid.

thread 'main' panicked at '`ninja` returned an error, please check the output for details.', skia-bindings\build_support\skia.rs:609:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.


c:\projects\rust-skia>
```

**Comment by photex** [comment]
Hrm... could this be a case of cmake bungling something?

I'm not running from a visual studio developer shell so it seems like it's picking up my clang/llvm install as the default compiler.

**Comment by photex** [comment]
OH! Scratch that... I don't have clang installed there!

It should be something like: `c:\Users\phote\scoop\shims\clang-cl.exe`

**Comment by pragmatrix** [comment]
Hmm, we currently hardcode the LLVM path to `C:/Program files/LLVM` on Windows. I suspect this needs to be fixed.

**Comment by photex** [comment]
This doesn't appear to be something in rust-skia (at least not something I see with a quick ripgrep). Where is this set? Is there perhaps an env var I could set? LLVM_HOME or something like that?

**Comment by pragmatrix** [comment]
Here: https://github.com/rust-skia/rust-skia/blob/master/skia-bindings/build_support/skia.rs#L297-L299

**Comment by photex** [comment]
Hrm... my rg fu failed me :P 
Alrighty, I'll put together a PR unless you already have a fix in mind that you'd prefer.

**Comment by pragmatrix** [comment]
go ahead!
