### ISSUE TITLE
Failed to run gl-window example

### ISSUE THREAD

**Issue by qingxiang-jia** [rust-skia/rust-skia#505]
I tried to run the example in my own project (build rust-skia directly is a bit hard so I did it in a new project, see the Cargo.toml file below).

From the error message:
`let mut gr_context = skia_safe::gpu::DirectContext::new_gl(None, None).unwrap();` panicked because `new_gl` returns a None which can't be unwrapped.

Full stack trace:
```
Pixel format of the window's GL context: PixelFormat { hardware_accelerated: true, color_bits: 24, alpha_bits: 8, depth_bits: 24, stencil_bits: 8, stereoscopy: false, double_buffer: true, multisampling: None, srgb: true }
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/main.rs:44:76
stack backtrace:
   0:     0x5598b2d7d680 - std::backtrace_rs::backtrace::libunwind::trace::h38f496e2f60ff056
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x5598b2d7d680 - std::backtrace_rs::backtrace::trace_unsynchronized::h56106da60d2adf4e
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5598b2d7d680 - std::sys_common::backtrace::_print_fmt::he96612ccef88d499
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x5598b2d7d680 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h7bc9abcb54e035e8
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x5598b2d9d3fc - core::fmt::write::hc902605fce7cd9d0
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/fmt/mod.rs:1096:17
   5:     0x5598b2d7a0c5 - std::io::Write::write_fmt::hc1b61b7b2ff05b80
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/io/mod.rs:1568:15
   6:     0x5598b2d7f805 - std::sys_common::backtrace::_print::hbfdf09e2f4163e71
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x5598b2d7f805 - std::sys_common::backtrace::print::h0f74697e38abc595
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x5598b2d7f805 - std::panicking::default_hook::{{closure}}::hddc95caf81a22541
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:208:50
   9:     0x5598b2d7f363 - std::panicking::default_hook::h3eba1f2638a2c835
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:225:9
  10:     0x5598b2d7ffa1 - std::panicking::rust_panic_with_hook::h8f88f1391abedf2a
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:591:17
  11:     0x5598b2d7fab7 - std::panicking::begin_panic_handler::{{closure}}::hf473b53e26f56dd7
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:495:13
  12:     0x5598b2d7db1c - std::sys_common::backtrace::__rust_end_short_backtrace::h6fde4603ccb02286
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x5598b2d7fa49 - rust_begin_unwind
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:493:5
  14:     0x5598b2d9b391 - core::panicking::panic_fmt::hac8c69602870cdf7
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/panicking.rs:92:14
  15:     0x5598b2d9b2dd - core::panicking::panic::h0ff31df2b71cdad9
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/panicking.rs:50:5
  16:     0x5598b248005c - core::option::Option<T>::unwrap::hf9802b071b62d646
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/option.rs:386:21
  17:     0x5598b2495f59 - skia_app::main::h39d21f2904827ffa
                               at /home/lee/Code/Projects/skia_app/src/main.rs:44:26
  18:     0x5598b242d10b - core::ops::function::FnOnce::call_once::h94d55e95646e85b3
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/ops/function.rs:227:5
  19:     0x5598b244a0be - std::sys_common::backtrace::__rust_begin_short_backtrace::h126d8386439ff57e
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/sys_common/backtrace.rs:125:18
  20:     0x5598b24a6ae1 - std::rt::lang_start::{{closure}}::h4bf1e94f3774c36f
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/rt.rs:66:18
  21:     0x5598b2d803c7 - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h6646ba386ff34dbe
                               at /build/rust/src/rustc-1.51.0-src/library/core/src/ops/function.rs:259:13
  22:     0x5598b2d803c7 - std::panicking::try::do_call::h47e376e14a330979
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:379:40
  23:     0x5598b2d803c7 - std::panicking::try::hb7ef6d6b3d4db346
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panicking.rs:343:19
  24:     0x5598b2d803c7 - std::panic::catch_unwind::h534d7ac891813066
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/panic.rs:431:14
  25:     0x5598b2d803c7 - std::rt::lang_start_internal::h8191eeb0dbee8736
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/rt.rs:51:25
  26:     0x5598b24a6ab7 - std::rt::lang_start::h01385e285ee268e8
                               at /build/rust/src/rustc-1.51.0-src/library/std/src/rt.rs:65:5
  27:     0x5598b249654a - main
  28:     0x7fce6c3bcb25 - __libc_start_main
  29:     0x5598b2419d6e - _start
  30:                0x0 - <unknown>
```

My Cargo file:
```
[package]
name = "skia_app"
version = "0.1.0"
authors = ["lee"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-bindings = "0.39.0"
skia-safe = { version = "0.39.0", features = ["gl"] }
glutin = "0.26.0"
gl = "0.14.0"
```

**Comment by ctrlcctrlv** [comment]
I'm disappointed I was not able to fix this for you, but I can at least confirm it's also happening for me on Arch Linux.

```
cargo run --example gl-window --features "gl"
```

Results in identical crash as OP.

Through adding `fprintf` macro, I was able to confirm that `GrDirectContext::MakeGL` is returning `(nil)`. Maybe calling convention is wrong.

**Comment by pragmatrix** [comment]
Skia seems to need to know about the Window Manager protocol in use. When I run the example with `--features "x11"` (which implies `gl`), the example works on the Ubuntu 20 VM I am testing with.

**Comment by qingxiang-jia** [comment]
Thank you both for the help. I tried to add "x11" as a feature but I got another issue: the build script tries to download `0.39.0/0bfa308c9780ab09043e-x86_64-unknown-linux-gnu-gl-x11` but it doesn't exist.

I checked the assets of the [release page](https://github.com/rust-skia/skia-binaries/releases/), it seems we indeed doesn't have `0bfa308c9780ab09043e-x86_64-unknown-linux-gnu-gl-x11` but we do have `skia-binaries-ab90feb7cb476f29c1b7-x86_64-unknown-linux-gnu-gl-x11.tar.gz`. The difference is the commit hash. I am new to this project, and I am not sure why we have different commit hash for one release. But putting that aside, it sounds like I need to somehow let the build script use `ab90feb7cb476f29c1b7` one.

**Comment by pragmatrix** [comment]
The binaries with the features `gl-x11` and `gl-textlayout-x11` were a test build. On Ubuntu they seem to work as expected. You should be able to run the `gl-window` on your distribution by checking out the rust-skia commit ab90feb7cb476f29c1b712fe1652101fa3f8865b and running:
```
FORCE_SKIA_BINARIES_DOWNLOAD=1 cargo run --example gl-window --features "x11" -vv
```

I will bump versions in master and prepare a new release.

**Comment by qingxiang-jia** [comment]
Thanks for the help. I am going to try it after you cut the release. (You can close the issue if you want.) Going through the Skia building process is a bit too much for me.

**Comment by pragmatrix** [comment]
`FORCE_SKIA_BINARIES_DOWNLOAD` shouldn't trigger a full build. Besides of that, the release with the new Linux X11 binaries is on crates.io. Version number is `0.39.1`: https://github.com/rust-skia/rust-skia/releases/tag/0.39.1

**Comment by qingxiang-jia** [comment]
Thank you! I followed your instruction and it worked flawlessly!
