### ISSUE TITLE
failed to run custom build command for `skia-bindings v0.42.1` for w10，add feature: `textlayout`

### ISSUE THREAD

**Issue by magicLaLa** [rust-skia/rust-skia#580]
`cargo build` is fail，How can i fix it ?

```toml
[package]
name = "canvas"
version = "0.1.1"
edition = "2021"

[dependencies]
skia-safe = { version ="0.42.0" , features=["webp-decode","binary-cache", "textlayout"] }
```

```bash
   Compiling skia-bindings v0.42.1
error: failed to run custom build command for `skia-bindings v0.42.1`

Caused by:
  process didn't exit successfully: `E:\Yinge\ycanvas\target\debug\build\skia-bindings-0d52c2409563c407\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.42.1/8b53a6e3e746b7456997-x86_64-pc-windows-msvc-textlayout-webpd
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.42.1/skia-binaries-8b53a6e3e746b7456997-x86_64-pc-windows-msvc-textlayout-webpd.tar.gz
  DOWNLOAD AND INSTALL FAILED: https://github.com/rust-skia/skia-binaries/releases/download/0.42.1/skia-binaries-8b53a6e3e746b7456997-x86_64-pc-windows-msvc-textlayout-webpd.tar.gz: status code 404
  STARTING A FULL BUILD
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=VCINSTALLDIR
  cargo:rerun-if-env-changed=LLVM_HOME
  cargo:rerun-if-env-changed=USERPROFILE
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Probing 'python2'

  --- stderr
  Checking for "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
  Checking for "C:\\LLVM\\bin\\clang-cl.exe"
  Checking for "C:\\Users\\MSI\\scoop\\apps\\llvm\\current\\bin\\clang-cl.exe"
  thread 'main' panicked at '>>>>> Probing for Python 2 failed, please make sure that it's available in PATH, probed executables are: ["python", "python2"] <<<<<', C:\Users\MSI\.cargo\registry\src\github.com-1ecc6299db9ec823\skia-bindings-0.42.1\build_support\skia\config.rs:410:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```bash
➜  python
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

**Comment by ctrlcctrlv** [comment]
As stated, you need the deprecated Python **2**, not Python 3.

**Comment by magicLaLa** [comment]
> As stated, you need the deprecated Python **2**, not Python 3.

Doesn't this need to use python2？After I installed python2，The output :

```bash
   Compiling skia-bindings v0.42.1
error: failed to run custom build command for `skia-bindings v0.42.1`

Caused by:
  process didn't exit successfully: `E:\Yinge\ycanvas\target\debug\build\skia-bindings-51b0fb69196191c9\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.42.1/8b53a6e3e746b7456997-x86_64-pc-windows-msvc-textlayout-webpd
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.42.1/skia-binaries-8b53a6e3e746b7456997-x86_64-pc-windows-msvc-textlayout-webpd.tar.gz
  DOWNLOAD AND INSTALL FAILED: https://github.com/rust-skia/skia-binaries/releases/download/0.42.1/skia-binaries-8b53a6e3e746b7456997-x86_64-pc-windows-msvc-textlayout-webpd.tar.gz: status code 404
  STARTING A FULL BUILD
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CXX
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=VCINSTALLDIR
  cargo:rerun-if-env-changed=LLVM_HOME
  cargo:rerun-if-env-changed=USERPROFILE
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Probing 'python2'
  Python 2 found: "python2"
  Synchronizing Skia dependencies
  Skipping "../src".
  Skipping "bin".
  skia\third_party/externals/libgif... > fd59fa92a0c86788dcdd84d091e1ce81eda06a77
  skia\third_party/externals/zlib      > c876c8f87101c5a75f6014b0f832499afeb65b73
  skia\third_party/externals/d3d12a... > 169895d529dfce00390a20e69c2f516066fe7a3b
  skia\third_party/externals/piex      > bb217acdca1cc0c16b704669dd6f91a1b509c406
  skia\third_party/externals/expat     > a28238bdeebc087071777001245df1876a11f5ee
  skia\third_party/externals/libwebp   > fedac6cc69cda3e9e04b780d324cf03921fb3ff4
  skia\third_party/externals/freetype  > d3dc2da9b27af5b90575d62989389cc65fe7977c
  skia\third_party/externals/harfbuzz  > 3a74ee528255cc027d84b204a87b5c25e47bff79
  skia\third_party/externals/libpng    > 386707c6d19b974ca2e3db7f5c61873813c6fe44
  skia\third_party/externals/icu       > a0718d4f121727e30b8d52c7a189ebf5ab52421f
  --- stderr
  Checking for "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
  Checking for "C:\\LLVM\\bin\\clang-cl.exe"
  Checking for "C:\\Users\\MSI\\scoop\\apps\\llvm\\current\\bin\\clang-cl.exe"
  Traceback (most recent call last):
    File "skia\bin\fetch-gn", line 26, in <module>
      cpu = {'amd64': 'amd64', 'arm64': 'arm64', 'x86_64': 'amd64', 'aarch64': 'arm64'}[platform.machine().lower()]
  KeyError: ''
  Traceback (most recent call last):
    File "skia/tools/git-sync-deps", line 266, in <module>
      exit(main(sys.argv[1:]))
    File "skia/tools/git-sync-deps", line 261, in main
      os.path.join(os.path.dirname(deps_file_path), 'bin', 'fetch-gn')])
    File "C:\Users\MSI\scoop\apps\python27\current\lib\subprocess.py", line 190, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\MSI\\scoop\\apps\\python27\\current\\python.exe', 'skia\\bin\\fetch-gn']' returned non-zero exit status 1
  thread 'main' panicked at '`skia/tools/git-sync-deps` failed', C:\Users\MSI\.cargo\registry\src\rsproxy.cn-8f6827c7555bfaf8\skia-bindings-0.42.1\build_support\skia\config.rs:321:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by ctrlcctrlv** [comment]
Well, what is `platform.machine()`?

**Comment by magicLaLa** [comment]
output: ''; 😂
Is the output of `KeyError`

**Comment by ctrlcctrlv** [comment]
And is your machine expected to have a normal result there? That is to say, it's not ARM or 32-bit, right? It's also possible that even if 64-bit, that a new Windows API was added for it post-Python2 deprecation, so Python2 can't get your version but Python3 can. What is your `platform.machine()` on Python3?

You may need to add a startup script. Like this

```
[fred@🍇葡萄🍇~]$ PYTHONSTARTUP=/tmp/startup.py python2
Python 2.7.18 (default, Oct 10 2021, 22:29:32) 
[GCC 11.1.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
'fake'
>>>
[fred@🍇葡萄🍇~]$ cat $PYTHONSTARTUP
```
```python
#!/usr/bin/env python
import platform

platform.machine = lambda: "fake"
```

**Comment by magicLaLa** [comment]
> And is your machine expected to have a normal result there? That is to say, it's not ARM or 32-bit, right? It's also possible that even if 64-bit, that a new Windows API was added for it post-Python2 deprecation, so Python2 can't get your version but Python3 can. What is your on Python3?`platform.machine()`
> 
> You may need to add a startup script. Like this
> 
> ```
> [fred@🍇葡萄🍇~]$ PYTHONSTARTUP=/tmp/startup.py python2
> Python 2.7.18 (default, Oct 10 2021, 22:29:32) 
> [GCC 11.1.0] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import platform
> >>> platform.machine()
> 'fake'
> >>>
> [fred@🍇葡萄🍇~]$ cat $PYTHONSTARTUP
> ```
> 
> ```python
> #!/usr/bin/env python
> import platform
> 
> platform.machine = lambda: "fake"
> ```

system is 64_bit

```bash
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import platform
>>> platform.machine()
''
```
I try to change it manually ，Then take a look 😂

**Comment by ctrlcctrlv** [comment]
> system is 64_bit

OK, but what is your platform.machine() on Python3?

**Comment by magicLaLa** [comment]
> > system is 64_bit
> 
> OK, but what is your platform.machine() on Python3?

` platform.machine()` is ' ' ;

it appeared again other errors，I am going to switch to wsl or macos  😂

**Comment by ln-12** [comment]
Hey, I got the same error which is initially shown, the output of `platform.machine()` is `'arm64'` for python 3 on my machine.

**Comment by ilopX** [comment]
I am getting the same error.

```bat
 Compiling skia-bindings v0.54.0 (D:\downloads\rust-skia\skia-bindings)
error: failed to run custom build command for `skia-bindings v0.54.0 (D:\downloads\rust-skia\skia-bindings)`

Caused by:
  process didn't exit successfully: `D:\downloads\rust-skia\target\debug\build\skia-bindings-bea55b006a9495e0\build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=CLANGCC
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CLANGCXX
  cargo:rerun-if-env-changed=CXX
  HOST: x86_64-pc-windows-msvc
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SDKTARGETSYSROOT
  cargo:rerun-if-env-changed=SDKROOT
  cargo:rerun-if-env-changed=VCINSTALLDIR
  cargo:rerun-if-env-changed=LLVM_HOME
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 3 found: "python"
  Synchronizing Skia dependencies
  Skipping "bin".
  skia\third_party/externals/brotli    @ e61745a6b7add50d380cfd7d3883dd6c62fc2c71
  ...ird_party/externals/libjpeg-turbo @ 22f1a22c99e9dde8cd3c72ead333f425c5a7aa77
  skia\third_party/externals/icu       @ a0718d4f121727e30b8d52c7a189ebf5ab52421f
  skia\third_party/externals/libpng    @ 386707c6d19b974ca2e3db7f5c61873813c6fe44
  ...rd_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
  skia\third_party/externals/expat     @ a28238bdeebc087071777001245df1876a11f5ee
  skia\third_party/externals/libwebp   @ a8e366166ab57bb1b4aaf6739fc775515bc71b51
  skia\third_party/externals/freetype  @ 275b116b40c9d183d42242099ea9ff276985855b
  ...third_party/externals/libgifcodec @ fd59fa92a0c86788dcdd84d091e1ce81eda06a77
  skia\third_party/externals/wuffs     @ 600cd96cf47788ee3a74b40a6028b035c9fd6a61
  skia\third_party/externals/piex      @ bb217acdca1cc0c16b704669dd6f91a1b509c406
  ...y/externals/vulkanmemoryallocator @ 7de5cc00de50e71a3aab22dea52fbb7ff4efceb6
  skia\third_party/externals/zlib      @ c876c8f87101c5a75f6014b0f832499afeb65b73
  ...third_party/externals/spirv-cross @ d8d051381f65b9606fb8016c79b7c3bab872eec3
  skia\third_party/externals/harfbuzz  @ 858570b1d9912a1b746ab39fbe62a646c4f7a5b1
  Skia args: is_official_build=true is_debug=false skia_enable_svg=false skia_enable_gpu=true skia_enable_skottie=false skia_use_gl=true skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_icu=false skia_use_system_libjpeg_turbo=false win_vc="C:\Program Files\Microsoft Visual Studio\2022\Community\VC" clang_win="c:\Program Files\LLVM\" target_cpu="x86_64" skia_use_expat=true skia_use_system_expat=false extra_cflags=["/MD","--target=x86_64-pc-windows-msvc"] extra_asmflags=["--target=x86_64-pc-windows-msvc"]
  ERROR at the command-line "--args":1:587: Invalid token.
  is_official_build=true is_debug=false skia_enable_svg=false skia_enable_gpu=true skia_enable_skottie=false skia_use_gl=true skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_icu=false skia_use_system_libjpeg_turbo=false win_vc="C:\Program Files\Microsoft Visual Studio\2022\Community\VC" clang_win="c:\Program Files\LLVM\" target_cpu="x86_64" skia_use_expat=true skia_use_system_expat=false extra_cflags=["/MD","--target=x86_64-pc-windows-msvc"] extra_asmflags=["--target=x86_64-pc-windows-msvc"]
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ^
  I have no idea what this is.

  --- stderr
  Checking for "c:\\Program Files\\LLVM\\bin\\clang-cl.exe"
  thread 'main' panicked at '""', skia-bindings\build_support\skia\config.rs:465:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

```
Windows [Version 10.0.18363.535]
Python 3.10.6

clang version 14.0.6
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: c:\Program Files\LLVM\bin

rustc 1.62.1 (e092d0b6b 2022-07-16)
rustup: stable-x86_64-pc-windows-msvc
```

**Comment by pragmatrix** [comment]
@ilopX This looks like different build error to me, most likely related to #314.

An because I am not sure the error happens with Python 3 we switched to recently, I am closing this issue.
