### ISSUE TITLE
Ninja build error Windows 11 x64 (WebAssembly build)

### ISSUE THREAD

**Issue by arnabanimesh** [rust-skia/rust-skia#619]
```
Skia args: is_official_build=true is_debug=false skia_enable_gpu=true skia_use_gl=true skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_icu=false skia_use_system_libjpeg_turbo=false cc="emcc" cxx="em++" skia_gl_standard="webgl" skia_use_freetype=true skia_use_system_freetype2=false skia_use_webgl=true target_cpu="wasm" skia_use_expat=true skia_use_system_expat=false extra_cflags=["-O3","--target=wasm32-unknown-emscripten"] extra_asmflags=["--target=wasm32-unknown-emscripten"]
  Done. Made 83 targets from 30 files in 1081ms
  ninja: Entering directory `C:\Users\arnab\Documents\coding\rust-skia\wasm-example\target\wasm32-unknown-emscripten\release\build\skia-bindings-739899b321181954\out\skia'
  [1/905] compile ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_android_parser.cpp
  FAILED: obj/src/ports/fontmgr_android.SkFontMgr_android_parser.o
  em++ -MD -MF obj/src/ports/fontmgr_android.SkFontMgr_android_parser.o.d -DNDEBUG -DSK_ENABLE_SKSL -DSK_ASSUME_WEBGL=1 -DSK_USE_WEBGL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -DXML_STATIC -I../../../../../../../../skia-bindings/skia -Wno-attributes -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -O3 --target=wasm32-unknown-emscripten -isystem C:/Users/arnab/Documents/coding/rust-skia/skia-bindings/skia/third_party/externals/expat/expat/lib -isystem C:/Users/arnab/Documents/coding/rust-skia/skia-bindings/skia/third_party/expat/include/expat_config -std=c++14 -Wno-c++17-extensions -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_android_parser.cpp -o obj/src/ports/fontmgr_android.SkFontMgr_android_parser.o
  CreateProcess failed: The system cannot find the file specified.
  [2/905] compile ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_android.cpp
  FAILED: obj/src/ports/fontmgr_android.SkFontMgr_android.o
  em++ -MD -MF obj/src/ports/fontmgr_android.SkFontMgr_android.o.d -DNDEBUG -DSK_ENABLE_SKSL -DSK_ASSUME_WEBGL=1 -DSK_USE_WEBGL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -DXML_STATIC -I../../../../../../../../skia-bindings/skia -Wno-attributes -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -O3 --target=wasm32-unknown-emscripten -isystem C:/Users/arnab/Documents/coding/rust-skia/skia-bindings/skia/third_party/externals/expat/expat/lib -isystem C:/Users/arnab/Documents/coding/rust-skia/skia-bindings/skia/third_party/expat/include/expat_config -std=c++14 -Wno-c++17-extensions -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_android.cpp -o obj/src/ports/fontmgr_android.SkFontMgr_android.o
  CreateProcess failed: The system cannot find the file specified.
  [3/905] compile ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_custom_directory.cpp
  FAILED: obj/src/ports/fontmgr_custom_directory.SkFontMgr_custom_directory.o
  em++ -MD -MF obj/src/ports/fontmgr_custom_directory.SkFontMgr_custom_directory.o.d -DNDEBUG -DSK_ENABLE_SKSL -DSK_ASSUME_WEBGL=1 -DSK_USE_WEBGL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../../../../../../../../skia-bindings/skia -Wno-attributes -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -O3 --target=wasm32-unknown-emscripten -std=c++14 -Wno-c++17-extensions -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_custom_directory.cpp -o obj/src/ports/fontmgr_custom_directory.SkFontMgr_custom_directory.o
  CreateProcess failed: The system cannot find the file specified.
  [4/905] compile ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_custom.cpp
  FAILED: obj/src/ports/fontmgr_custom.SkFontMgr_custom.o
  em++ -MD -MF obj/src/ports/fontmgr_custom.SkFontMgr_custom.o.d -DNDEBUG -DSK_ENABLE_SKSL -DSK_ASSUME_WEBGL=1 -DSK_USE_WEBGL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../../../../../../../../skia-bindings/skia -Wno-attributes -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -O3 --target=wasm32-unknown-emscripten -std=c++14 -Wno-c++17-extensions -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_custom.cpp -o obj/src/ports/fontmgr_custom.SkFontMgr_custom.o
  CreateProcess failed: The system cannot find the file specified.
  [5/905] compile ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_custom_directory_factory.cpp
  FAILED: obj/src/ports/fontmgr_custom_directory_factory.SkFontMgr_custom_directory_factory.o
  em++ -MD -MF obj/src/ports/fontmgr_custom_directory_factory.SkFontMgr_custom_directory_factory.o.d -DNDEBUG -DSK_ENABLE_SKSL -DSK_ASSUME_WEBGL=1 -DSK_USE_WEBGL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../../../../../../../../skia-bindings/skia -Wno-attributes -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -O3 --target=wasm32-unknown-emscripten -std=c++14 -Wno-c++17-extensions -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_custom_directory_factory.cpp -o obj/src/ports/fontmgr_custom_directory_factory.SkFontMgr_custom_directory_factory.o
  CreateProcess failed: The system cannot find the file specified.
  [6/905] compile ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_custom_embedded.cpp
  FAILED: obj/src/ports/fontmgr_custom_embedded.SkFontMgr_custom_embedded.o
  em++ -MD -MF obj/src/ports/fontmgr_custom_embedded.SkFontMgr_custom_embedded.o.d -DNDEBUG -DSK_ENABLE_SKSL -DSK_ASSUME_WEBGL=1 -DSK_USE_WEBGL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../../../../../../../../skia-bindings/skia -Wno-attributes -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -O3 --target=wasm32-unknown-emscripten -std=c++14 -Wno-c++17-extensions -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_custom_embedded.cpp -o obj/src/ports/fontmgr_custom_embedded.SkFontMgr_custom_embedded.o
  CreateProcess failed: The system cannot find the file specified.
  [7/905] compile ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_custom_empty.cpp
  FAILED: obj/src/ports/fontmgr_custom_empty.SkFontMgr_custom_empty.o
  em++ -MD -MF obj/src/ports/fontmgr_custom_empty.SkFontMgr_custom_empty.o.d -DNDEBUG -DSK_ENABLE_SKSL -DSK_ASSUME_WEBGL=1 -DSK_USE_WEBGL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -I../../../../../../../../skia-bindings/skia -Wno-attributes -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -O3 --target=wasm32-unknown-emscripten -std=c++14 -Wno-c++17-extensions -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_custom_empty.cpp -o obj/src/ports/fontmgr_custom_empty.SkFontMgr_custom_empty.o
  CreateProcess failed: The system cannot find the file specified.

  --- stderr
  ninja: fatal: ReadFile: The handle is invalid.

  thread 'main' panicked at '`ninja` returned an error, please check the output for details.', C:\Users\arnab\Documents\coding\rust-skia\skia-bindings\build_support\skia\config.rs:407:5
  stack backtrace:
     0:     0x7ff659aaf73f - std::backtrace_rs::backtrace::dbghelp::trace
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\..\..\backtrace\src\backtrace\dbghelp.rs:98
     1:     0x7ff659aaf73f - std::backtrace_rs::backtrace::trace_unsynchronized
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\..\..\backtrace\src\backtrace\mod.rs:66
     2:     0x7ff659aaf73f - std::sys_common::backtrace::_print_fmt
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:67
     3:     0x7ff659aaf73f - std::sys_common::backtrace::_print::impl$0::fmt
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:46
     4:     0x7ff659ad2a5a - core::fmt::write
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\core\src\fmt\mod.rs:1168
     5:     0x7ff659aa4ed8 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\io\mod.rs:1660
     6:     0x7ff659ab24eb - std::sys_common::backtrace::_print
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:49
     7:     0x7ff659ab24eb - std::sys_common::backtrace::print
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\sys_common\backtrace.rs:36
     8:     0x7ff659ab24eb - std::panicking::default_hook::closure$1
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:211
     9:     0x7ff659ab1fe4 - std::panicking::default_hook
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:228
    10:     0x7ff659ab29ec - std::panicking::rust_panic_with_hook
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:606
    11:     0x7ff65959af81 - std::panicking::begin_panic::{{closure}}::hb8391563a36ddd82
    12:     0x7ff6595b19af - std::sys_common::backtrace::__rust_end_short_backtrace::h55742916fdb6ca7c
    13:     0x7ff65959aefd - std::panicking::begin_panic::h730b5c040e37d4f8
    14:     0x7ff659356bb5 - build_script_build::build_support::skia::config::configure_skia::{{closure}}::h0ec3ea313cd5dc31
    15:     0x7ff659355c5a - build_script_build::build_support::skia::config::build::hd8a6dbade38cef60
    16:     0x7ff65934629c - build_script_build::build_support::binary_cache::git::trim_hash::h0bf1b7d45d76b1c7
    17:     0x7ff6593467d0 - build_script_build::build_support::binary_cache::git::trim_hash::h0bf1b7d45d76b1c7
    18:     0x7ff659356e06 - core::ops::function::FnOnce::call_once::h5437fb33a7c9c3d2
    19:     0x7ff6593635d7 - std::rt::lang_start::{{closure}}::h694c8c439485068d
    20:     0x7ff6593635ac - std::rt::lang_start::{{closure}}::h694c8c439485068d
    21:     0x7ff659aaef9f - core::ops::function::impls::impl$2::call_once
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\library\core\src\ops\function.rs:259
    22:     0x7ff659aaef9f - std::panicking::try::do_call
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:406
    23:     0x7ff659aaef9f - std::panicking::try
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:370
    24:     0x7ff659aaef9f - std::panic::catch_unwind
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panic.rs:133
    25:     0x7ff659aaef9f - std::rt::lang_start_internal::closure$2
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\rt.rs:128
    26:     0x7ff659aaef9f - std::panicking::try::do_call
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:406
    27:     0x7ff659aaef9f - std::panicking::try
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panicking.rs:370
    28:     0x7ff659aaef9f - std::panic::catch_unwind
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\panic.rs:133
    29:     0x7ff659aaef9f - std::rt::lang_start_internal
                                 at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a\/library\std\src\rt.rs:128
    30:     0x7ff659363590 - std::rt::lang_start::hbbd8da6430756ac6
    31:     0x7ff6593492c6 - main
    32:     0x7ff659aec580 - invoke_main
                                 at d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:78
    33:     0x7ff659aec580 - __scrt_common_main_seh
                                 at d:\a01\_work\20\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288
    34:     0x7fff973654e0 - BaseThreadInitThunk
    35:     0x7fff985e485b - RtlUserThreadStart
```

I tried running the commands separately and it generated the object files. But ninja fails to create and recognize

**Comment by arnabanimesh** [comment]
During the initial build, the error was something like this
```
Skia args: is_official_build=true is_debug=false skia_enable_gpu=true skia_use_gl=true skia_use_egl=false skia_use_x11=false skia_use_system_libpng=false skia_use_libwebp_encode=false skia_use_libwebp_decode=false skia_use_system_zlib=false skia_use_xps=false skia_use_dng_sdk=false cc="clang" cxx="clang++" skia_use_icu=false skia_use_system_libjpeg_turbo=false cc="emcc" cxx="em++" skia_gl_standard="webgl" skia_use_freetype=true skia_use_system_freetype2=false skia_use_webgl=true target_cpu="wasm" skia_use_expat=true skia_use_system_expat=false extra_cflags=["-O3","--target=wasm32-unknown-emscripten"] extra_asmflags=["--target=wasm32-unknown-emscripten"]
  Done. Made 83 targets from 30 files in 1320ms
  ninja: Entering directory `C:\Users\arnab\Documents\coding\rust-skia\wasm-example\target\wasm32-unknown-emscripten\release\build\skia-bindings-739899b321181954\out\skia'
  [1/916] stamp obj/android_utils.stamp
  [2/916] stamp obj/arm64.stamp
  [3/916] stamp obj/armv7.stamp
  [4/916] compile ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_android.cpp
  FAILED: obj/src/ports/fontmgr_android.SkFontMgr_android.o
  em++ -MD -MF obj/src/ports/fontmgr_android.SkFontMgr_android.o.d -DNDEBUG -DSK_ENABLE_SKSL -DSK_ASSUME_WEBGL=1 -DSK_USE_WEBGL -DSK_GAMMA_APPLY_TO_A8 -DSKIA_IMPLEMENTATION=1 -DXML_STATIC -I../../../../../../../../skia-bindings/skia -Wno-attributes -fstrict-aliasing -fPIC -fvisibility=hidden -O3 -fdata-sections -ffunction-sections -O3 --target=wasm32-unknown-emscripten -isystem C:/Users/arnab/Documents/coding/rust-skia/skia-bindings/skia/third_party/externals/expat/expat/lib -isystem C:/Users/arnab/Documents/coding/rust-skia/skia-bindings/skia/third_party/expat/include/expat_config -std=c++14 -Wno-c++17-extensions -fvisibility-inlines-hidden -fno-exceptions -fno-rtti -c ../../../../../../../../skia-bindings/skia/src/ports/SkFontMgr_android.cpp -o obj/src/ports/fontmgr_android.SkFontMgr_android.o
  CreateProcess failed: The system cannot find the file specified.
  [5/916] stamp obj/compile_sksl_glsl_nosettings_tests.stamp
  [6/916] stamp obj/compile_sksl_glsl_tests.stamp
  [7/916] stamp obj/crc32.stamp
  [8/916] stamp obj/avx.stamp
  [9/916] stamp obj/compile_sksl_spirv_tests.stamp
  [10/916] stamp obj/compile_sksl_metal_tests.stamp
  [11/916] stamp obj/compile_sksl_skvm_tests.stamp
  [12/916] stamp obj/dehydrate_sksl.stamp
  [13/916] stamp obj/fontmgr_FontConfigInterface.stamp
  ninja: build stopped: subcommand failed.

  --- stderr
  thread 'main' panicked at '`ninja` returned an error, please check the output for details.', C:\Users\arnab\Documents\coding\rust-skia\skia-bindings\build_support\skia\config.rs:407:5
```

**Comment by learnplaycreate** [comment]
having the same issue trying to build the wasm-example

**Comment by learnplaycreate** [comment]
I'll just preface this by saying that I have no experience at all in either rust, C, or C++
but had this error when I was attempting to build the wasm example and it took me ages to figure it out - so thought i'd add my solution incase it helps. 
I found the make file in the wasm example points to a particular install of emscripten, and when I changed that to point at my actual install the error was resolved.

**Comment by arnabanimesh** [comment]
Are you building on windows? I had to build llvm from scratch just to make emcc work.

This error is related to `ninja-command` system call which prints a success message regarding `depot_tools`
