### ISSUE TITLE
TLS Cert issue when trying to download prebuilt file

### ISSUE THREAD

**Issue by jamischarles** [rust-skia/rust-skia#654]
Hey folks!

I run into a cert issue when trying to download skia bindings as part of deps for neovide project:
https://github.com/neovide/neovide/discussions/1370

On my work laptop, they've installed their own self signed root cert.

This leads to the `tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer)` error.

In node/npm I can solve this via an env variable that points at the self signed cert:
`NODE_EXTRA_CA_CERTS=path_to_company_cert.pem npm install`

With cargo it seems that you can do the same with:
`CARGO_HTTP_CAINFO=path_to_company_cert.pem`

BUT, my error happens in a build script for `skia-bindings`.

```
 --- stderr
  thread 'main' panicked at 'Failed to download https://codeload.github.com/rust-skia/skia/tar.gz/m100-0.48.7 (https://codeload.github.com/rust-skia/skia/tar.gz/m100-0.48.7: Connection Failed: tls connection init failed: invalid peer certificate contents: invalid peer certificate: UnknownIssuer)', /Users/jacharles/.cargo/registry/src/github.com-1ecc6299db9ec823/skia-bindings-0.49.1/build_support/binary_cache/download.rs:67:35
  stack backtrace:
     0: rust_begin_unwind
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
     1: core::panicking::panic_fmt
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
     2: build_script_build::build_support::binary_cache::download::download_dependencies::{{closure}}
               at ./build_support/binary_cache/download.rs:67:35
     3: core::result::Result<T,E>::unwrap_or_else
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/result.rs:1464:23
     4: build_script_build::build_support::binary_cache::download::download_dependencies
               at ./build_support/binary_cache/download.rs:66:23
     5: build_script_build::build_support::binary_cache::download::resolve_dependencies
               at ./build_support/binary_cache/download.rs:17:9
     6: build_script_build::build_support::skia::config::build
               at ./build_support/skia/config.rs:348:9
     7: build_script_build::build_from_source
               at ./build.rs:39:5
     8: build_script_build::main
               at ./build.rs:127:13
     9: core::ops::function::FnOnce::call_once
               at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Any ideas for how I can tell the build script to use the company cert here?

Or any workarounds? I'm able to download the file manually via curl, but unsure how I can have the build script reference that downloaded file

Thanks!

**Comment by pragmatrix** [comment]
We switched the downloader for external files in the build process from ureq to invoking the curl command a few releases ago. This should have resolved this issue. Closing.
