### ISSUE TITLE
Build fails: skia-bindings 0.52.0] thread 'main' panicked at 'unsupported target: Target { architecture: "x86_64", vendor: "unknown", system: "freebsd", abi: None }', /usr/ports/editors/neovide/work/neovide-0.10.3/cargo-crates/skia-bindings-0.52.0/build_support/binaries_config.rs:118:18

### ISSUE THREAD

**Issue by yurivict** [rust-skia/rust-skia#753]
```
[skia-bindings 0.52.0] thread 'main' panicked at 'unsupported target: Target { architecture: "x86_64", vendor: "unknown", system: "freebsd", abi: None }', /usr/ports/editors/neovide/work/neovide-0.10.3/cargo-crates/skia-bindings-0.52.0/build_support/binaries_config.rs:118:18
[skia-bindings 0.52.0] stack backtrace:
[skia-bindings 0.52.0] cargo:rerun-if-env-changed=SKIA_DEBUG
[skia-bindings 0.52.0] note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: failed to run custom build command for `skia-bindings v0.52.0`

Caused by:
  process didn't exit successfully: `/usr/ports/editors/neovide/work/target/release/build/skia-bindings-dba0af6bf778d075/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=SKIA_DEBUG

  --- stderr
  thread 'main' panicked at 'unsupported target: Target { architecture: "x86_64", vendor: "unknown", system: "freebsd", abi: None }', /usr/ports/editors/neovide/work/neovide-0.10.3/cargo-crates/skia-bi
```

FreeBSD 13.1

**Comment by pragmatrix** [comment]
Moving this to discussions. There is no path I see how we can support FreeBSD right now. If someone wants this, they must go all in, which means: Make everything build including Skia (which is perhaps the hardest part) and add CI support. 

Related: https://github.com/neovide/neovide/issues/1294
