### ISSUE TITLE
`Surface::from_backend_render_target` returns `None`

### ISSUE THREAD

**Issue by Speykious** [rust-skia/rust-skia#764]
I was trying to create a Skia hello-world window using glutin's latest API, which dissociates glutin from winit and raw-window-handle, but I couldn't arrive at a working window.
Instead, it panics with the following:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', examples/mao-blur.rs:53:6
```

## Dependencies

```toml
[dependencies]
glow = "0.12.0"
glutin = "0.30.3"
glutin-winit = "0.2.2"
raw-window-handle = "0.5.0"
skia-safe = { version = "0.58.0", features = ["x11", "gl"] }
winit = "0.27.5"
```

## Code

```rs
use std::error::Error;
use std::ffi::CString;
use std::num::NonZeroU32;

use glow::HasContext;
use glutin::config::{Config, ConfigTemplateBuilder};
use glutin::context::{ContextApi, ContextAttributesBuilder, Version};
use glutin::display::GetGlDisplay;
use glutin::prelude::{GlConfig, GlDisplay, NotCurrentGlContextSurfaceAccessor};
use glutin::surface::{GlSurface, SurfaceAttributesBuilder};
use glutin_winit::ApiPrefence;
use raw_window_handle::HasRawWindowHandle;
use skia_safe::gpu::gl::FramebufferInfo;
use skia_safe::gpu::{BackendRenderTarget, SurfaceOrigin};
use skia_safe::{Color, ColorType};
use winit::event::{Event, WindowEvent};
use winit::window::{Window, WindowBuilder};

// Guarantee the drop order inside the FnMut closure. `Window` _must_ be dropped after
// `DirectContext`.
//
// https://github.com/rust-skia/rust-skia/issues/476
struct SkiaEnv {
    surface: skia_safe::Surface,
    gr_context: skia_safe::gpu::DirectContext,
    window: Window,
}

fn create_surface(
    window: &Window,
    gl_config: &Config,
    fb_info: FramebufferInfo,
    gr_context: &mut skia_safe::gpu::DirectContext,
) -> skia_safe::Surface {
    let size = window.inner_size();
    let backend_render_target = BackendRenderTarget::new_gl(
        (
            size.width.try_into().unwrap(),
            size.height.try_into().unwrap(),
        ),
        gl_config.num_samples() as usize,
        gl_config.stencil_size() as usize,
        fb_info,
    );
    skia_safe::Surface::from_backend_render_target(
        gr_context,
        &backend_render_target,
        SurfaceOrigin::BottomLeft,
        ColorType::RGBA8888,
        None,
        None,
    )
    .unwrap()
}

#[allow(clippy::unusual_byte_groupings)]
fn main() -> Result<(), Box<dyn Error>> {
    /////////////////////////////////////
    //// glutin-winit initialization ////
    /////////////////////////////////////

    let events = winit::event_loop::EventLoop::new();

    let window_builder = WindowBuilder::new()
        .with_transparent(false)
        .with_resizable(true)
        .with_inner_size(winit::dpi::PhysicalSize::new(1024, 768))
        .with_title("Swash demo");

    let (window, gl_config) = glutin_winit::DisplayBuilder::new()
        .with_preference(ApiPrefence::FallbackEgl)
        .with_window_builder(Some(window_builder))
        .build(&events, ConfigTemplateBuilder::default(), |configs| {
            configs
                .filter(|c| c.srgb_capable())
                .max_by_key(|c| c.num_samples())
                .unwrap()
        })?;

    let window = window.unwrap(); // set in display builder
    let raw_window_handle = window.raw_window_handle();
    let gl_display = gl_config.display();

    let context_attributes = ContextAttributesBuilder::new()
        .with_context_api(ContextApi::OpenGl(Some(Version::new(3, 1))))
        .with_profile(glutin::context::GlProfile::Core)
        .build(Some(raw_window_handle));

    let dimensions = window.inner_size();

    let (gl_surface, gl_ctx) = {
        let attrs = SurfaceAttributesBuilder::<glutin::surface::WindowSurface>::new().build(
            raw_window_handle,
            NonZeroU32::new(dimensions.width).unwrap(),
            NonZeroU32::new(dimensions.height).unwrap(),
        );

        let surface = unsafe { gl_display.create_window_surface(&gl_config, &attrs) }?;
        let context = unsafe { gl_display.create_context(&gl_config, &context_attributes) }?
            .make_current(&surface)?;
        (surface, context)
    };

    // Load the OpenGL function pointers
    let gl = unsafe {
        glow::Context::from_loader_function(|symbol| {
            gl_display.get_proc_address(&CString::new(symbol).unwrap()) as *const _
        })
    };

    //////////////////////////////////
    //// skia-safe initialization ////
    //////////////////////////////////

    let mut gr_context = skia_safe::gpu::DirectContext::new_gl(None, None).unwrap();

    let fb_info = FramebufferInfo {
        fboid: unsafe { gl.get_parameter_i32(glow::FRAMEBUFFER_BINDING) } as u32,
        format: skia_safe::gpu::gl::Format::RGBA8 as u32,
    };

    let surface = create_surface(&window, &gl_config, fb_info, &mut gr_context);

    let mut env = SkiaEnv {
        surface,
        gr_context,
        window,
    };

    ////////////////////
    //// event loop ////
    ////////////////////

    events.run(move |event, _, control_flow| {
        control_flow.set_poll();
        match event {
            Event::LoopDestroyed => (),
            Event::WindowEvent { event, .. } => match event {
                WindowEvent::Resized(physical_size) => {
                    env.surface =
                        create_surface(&env.window, &gl_config, fb_info, &mut env.gr_context);

                    gl_surface.resize(
                        &gl_ctx,
                        NonZeroU32::new(physical_size.width).unwrap(),
                        NonZeroU32::new(physical_size.height).unwrap(),
                    );
                }
                WindowEvent::CloseRequested => control_flow.set_exit(),
                _ => (),
            },
            Event::MainEventsCleared => {
                env.window.request_redraw();
            }
            Event::RedrawRequested(_) => {
                {
                    let canvas = env.surface.canvas();
                    canvas.clear(Color::from(0xff_161a1d));
                }
                env.gr_context.flush(None);
                gl_surface.swap_buffers(&gl_ctx).unwrap();
            }
            _ => (),
        }
    })
}
```

What could be the cause of the error? Is the stencil buffer size wrong, or the multisampling?
It is to be noted that the current `gl-window` example works on my machine and I have some older code that uses the old glutin API with Skia which still works.

**Comment by tronical** [comment]
IIRC I had a similar issue.  I think in your code the issue could be this:

```rust
let mut gr_context = skia_safe::gpu::DirectContext::new_gl(None, None).unwrap();
```

I think the first argument should not be empty.

This is what we do and pass as first argument:

```

};

        let gl_interface = skia_safe::gpu::gl::Interface::new_load_with(|name| {
            current_glutin_context
                .display()
                .get_proc_address(&std::ffi::CString::new(name).unwrap()) as *const _
        });
```

**Comment by Speykious** [comment]
@tronical Thanks for your help :D

I tried now to create the `gl_interface`, but it produces a segmentation fault.

I don't exactly know how to plug the `gl_interface` along with the framebuffer info, but it seeems to me that calling `get_proc_address` twice might be a problem?

```rs
    // Load the OpenGL function pointers
    let gl = unsafe {
        glow::Context::from_loader_function(|symbol| {
            gl_display.get_proc_address(&CString::new(symbol).unwrap()) as *const _
        })
    };

    //////////////////////////////////
    //// skia-safe initialization ////
    //////////////////////////////////

    let gl_interface = skia_safe::gpu::gl::Interface::new_load_with(|name| {
        gl_display.get_proc_address(&std::ffi::CString::new(name).unwrap()) as *const _
    });

    let mut gr_context = skia_safe::gpu::DirectContext::new_gl(gl_interface, None).unwrap();

    let fb_info = FramebufferInfo {
        fboid: unsafe { gl.get_parameter_i32(glow::FRAMEBUFFER_BINDING) } as u32,
        format: skia_safe::gpu::gl::Format::RGBA8 as u32,
    };

    let surface = create_surface(&window, &gl_config, fb_info, &mut gr_context);
```

**Comment by Speykious** [comment]
![image](https://user-images.githubusercontent.com/13885008/215262859-b13d08f4-ae33-4cf8-bdec-2ca56d7725b2.png)

Hmmm. It seems to be wanting to use EGL.
So I tried switching to EGL like this:
```rs
    let (window, gl_config) = glutin_winit::DisplayBuilder::new()
        .with_preference(ApiPrefence::PreferEgl)

    // snip

    let context_attributes = ContextAttributesBuilder::new()
        .with_context_api(ContextApi::Gles(None))
        // .with_profile(glutin::context::GlProfile::Core)
        .build(Some(raw_window_handle));
```

I noticed that now all the symbols get loaded in both `get_proc_address` callers, but then I *again* get a panic at `Surface::from_backend_render_target`...
```rs
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', examples/mao-blur.rs:53:6
```

**Comment by marc2332** [comment]
Any update on this? I am getting it too

**Comment by pragmatrix** [comment]
@Speykious Selecting a configuration with `samples = 0` most likely will work, we have adjusted the gl-windows example in #783 accordingly in that it now selects configuration with the least number of samples available. Closing.
