### ISSUE TITLE
Can't build for Raspberry Pi Zero 2W (32 bits)

### ISSUE THREAD

**Issue by bernardolansing** [rust-skia/rust-skia#996]
I can't get `skia-bindings` to compile to the RPi Zero 2W. Its target triple is `armv7-unknown-linux-gnueabihf` (32 bits). Is that platform supported? I know there's no prebuilt binaries for it, but can't I build it myself? Here's the error log:

```
error: failed to run custom build command for `skia-bindings v0.75.0`

Caused by:
  process didn't exit successfully: `/home/proto006/rust-target/debug/build/skia-bindings-df4693983625562a/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=DOCS_RS
  cargo:rerun-if-env-changed=SKIA_DEBUG
  HOST: armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  cargo:rerun-if-env-changed=SKIA_SOURCE_DIR
  cargo:rerun-if-env-changed=FORCE_SKIA_BUILD
  cargo:rerun-if-env-changed=FORCE_SKIA_BINARIES_DOWNLOAD
  TRYING TO DOWNLOAD AND INSTALL SKIA BINARIES: 0.75.0/e7e538647512cab844c3-armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=SKIA_BINARIES_URL
    FROM: https://github.com/rust-skia/skia-binaries/releases/download/0.75.0/skia-binaries-e7e538647512cab844c3-armv7-unknown-linux-gnueabihf.tar.gz
  DOWNLOAD AND INSTALL FAILED: curl error code: Some(22)
  curl stderr: Ok("")
  STARTING A FULL BUILD
  cargo:rerun-if-env-changed=CLANGCC
  cargo:rerun-if-env-changed=CC
  cargo:rerun-if-env-changed=CLANGCXX
  cargo:rerun-if-env-changed=CXX
  HOST: armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=OPT_LEVEL
  cargo:rerun-if-env-changed=SKIA_USE_SYSTEM_LIBRARIES
  HOST: armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=SDKTARGETSYSROOT
  cargo:rerun-if-env-changed=SDKROOT
  HOST: armv7-unknown-linux-gnueabihf
  HOST: armv7-unknown-linux-gnueabihf
  HOST: armv7-unknown-linux-gnueabihf
  cargo:rerun-if-env-changed=SKIA_NINJA_COMMAND
  cargo:rerun-if-env-changed=SKIA_GN_COMMAND
  Probing 'python'
  Python 3 found: "python"
  Synchronizing Skia dependencies
  Skipping "bin".
  skia/third_party/externals/wuffs     @ e3f919ccfe3ef542cfc983a82146070258fb57f8
  skia/third_party/externals/brotli    @ 6d03dfbedda1615c4cba1211f8d81735575209c8
  skia/third_party/externals/libwebp   @ 845d5476a866141ba35ac133f856fa62f0b7445f
  ...rd_party/externals/d3d12allocator @ 169895d529dfce00390a20e69c2f516066fe7a3b
  skia/third_party/externals/expat     @ 441f98d02deafd9b090aea568282b28f66a50e36
  ...third_party/externals/spirv-cross @ b8fcf307f1f347089e3c46eb4451d27f32ebc8d3
  skia/third_party/externals/zlib      @ 646b7f569718921d7d4b5b8e22572ff6c76f2596
  skia/third_party/externals/icu       @ 364118a1d9da24bb5b770ac3d762ac144d6da5a4
  skia/third_party/externals/libpng    @ ed217e3e601d8e462f7fd1e04bed43ac42212429
  skia/third_party/externals/harfbuzz  @ b74a7ecc93e283d059df51ee4f46961a782bcdb8
  ...y/externals/vulkanmemoryallocator @ a6bfc237255a6bac1513f7c1ebde6d8aed6b5191
  ...ird_party/externals/libjpeg-turbo @ ed683925e4897a84b3bffc5c1414c85b97a129a3
  skia/third_party/externals/freetype  > a46424228f0998a72c715f32e18dca8a7a764c1f

  --- stderr
  Traceback (most recent call last):
    File "/home/proto006/.cargo/registry/src/index.crates.io-1cd66030c949c28d/skia-bindings-0.75.0/skia/bin/fetch-gn", line 23, in <module>
      cpu = {'aarch64': 'arm64', 'amd64': 'amd64', 'arm64': 'arm64', 'x86_64': 'amd64'}[platform.machine().lower()]
            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  KeyError: 'armv7l'
  Traceback (most recent call last):
    File "/home/proto006/.cargo/registry/src/index.crates.io-1cd66030c949c28d/skia-bindings-0.75.0/skia/tools/git-sync-deps", line 281, in <module>
      exit(main(sys.argv[1:]))
           ^^^^^^^^^^^^^^^^^^
    File "/home/proto006/.cargo/registry/src/index.crates.io-1cd66030c949c28d/skia-bindings-0.75.0/skia/tools/git-sync-deps", line 270, in main
      subprocess.check_call(
    File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/bin/python', 'skia/bin/fetch-gn']' returned non-zero exit status 1.
  thread 'main' panicked at /home/proto006/.cargo/registry/src/index.crates.io-1cd66030c949c28d/skia-bindings-0.75.0/build_support/skia/config.rs:282:9:
  `skia/tools/git-sync-deps` failed
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Forgive me if this information is already written somewhere, I must have missed it.

**Comment by pragmatrix** [comment]
> HOST: armv7-unknown-linux-gnueabihf
> ... fetch-gn ...
> KeyError: 'armv7l'

32-bit Windows targets seem to work. But I don't think that anyone has tried to build _on_ a 32-bit host. I suggest to start with a cross-compile from a 64-bit Ubuntu. Perhaps even Skia only first, and then work your way up.
