### ISSUE TITLE
building on windows arm64 fails, due to missing remote file

### ISSUE THREAD

**Issue by yashamon** [rust-skia/rust-skia#998]
Checking for "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
  Checking for "C:\\LLVM\\bin\\clang-cl.exe"
  Checking for "C:\\Users\\yasha\\scoop\\apps\\llvm\\current\\bin\\clang-cl.exe"
  Traceback (most recent call last):
    File "C:\Users\yasha\Cargo\git\checkouts\rust-skia-35c6c5f9d522ea9f\0a9683d\skia-bindings\skia\bin\fetch-gn", line 28, in <module>
      f.write(urlopen(url).read())
              ^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 215, in urlopen
      return opener.open(url, data, timeout)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 521, in open
      response = meth(req, response)
                 ^^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 630, in http_response
      response = self.parent.error(
                 ^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 559, in error
      return self._call_chain(*args)
             ^^^^^^^^^^^^^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 492, in _call_chain
      result = func(*args)
               ^^^^^^^^^^^
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\urllib\request.py", line 639, in http_error_default
      raise HTTPError(req.full_url, code, msg, hdrs, fp)
  urllib.error.HTTPError: HTTP Error 404: Not Found
  Traceback (most recent call last):
    File "C:\Users\yasha\Cargo\git\checkouts\rust-skia-35c6c5f9d522ea9f\0a9683d\skia-bindings\skia\tools\git-sync-deps", line 281, in <module>
      exit(main(sys.argv[1:]))
           ^^^^^^^^^^^^^^^^^^
    File "C:\Users\yasha\Cargo\git\checkouts\rust-skia-35c6c5f9d522ea9f\0a9683d\skia-bindings\skia\tools\git-sync-deps", line 270, in main
      subprocess.check_call(
    File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1264.0_x64__qbz5n2kfra8p0\Lib\subprocess.py", line 413, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['C:\\Users\\yasha\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\\python.exe', 'skia\\bin\\fetch-gn']' returned non-zero exit status 1.
  thread 'main' panicked at skia-bindings\build_support\skia\config.rs:282:9:
  `skia/tools/git-sync-deps` failed
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `skia-org v1.0.0 (https://github.com/rust-skia/rust-skia#0a9683d3)`, intermediate artifacts can be found at `C:\Users\yasha\AppData\Local\Temp\cargo-installsOHQuA`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

**Comment by fredizzimo** [comment]
I'm adding a bit of context here, this was originally reported in 
* https://github.com/neovide/neovide/issues/2655

I'm not sure if this is something `skia-rs` can fix itself or not, it looks like the arm64 package of `gn` is missing,    but maybe it's possible to patch it to use the x64 version of the tool, to run with the prism emulator.

**Comment by pragmatrix** [comment]
@fredizzimo Thank you for providing context, very appreciated!

Is it possible to get a gn.exe executable compiled and installed on arm64 independently of what binaries Google provides?

If so, there is the environment variable `SKIA_GN_COMMAND` which may won't work in this case, because git-sync-deps always seem to run fetch-gn, but if so a workaround should be fairly simple.

**Comment by fredizzimo** [comment]
I guess @yashamon could try the instructions here https://gn.googlesource.com/gn. If it's too complicated we could also setup some cross-compilation. At least I don't have a arm64 windows machine, well I don't have a development machine at all for one week more.

I guess they could also try downloading the regular exe manually and set `SKIA_GN_COMMAND` to point to it. The Arm64 has x64 emulation on Windows.

**Comment by yashamon** [comment]
I will try to set skia_gn_command, will let you know.
I already tried to compile gn from source, it fails at linking stage with
some error about x64, I don't know where that comes from, probably the
config has hard coded x64 stuff.

**Comment by yashamon** [comment]
I set the SKIA_GN_COMMAND but it still tries to download it.

**Comment by pragmatrix** [comment]
@yashamon I suspected before git-sync-deps always calls into fetch-gn. #999 tries to prevent that if SKIA_GN_COMMAND is set. Can you try from this branch to see if that works now as expected?

**Comment by pragmatrix** [comment]
Ah, sry, there is an unexpected side effect in #999. I need to figure out while CI is not working first.

**Comment by tronical** [comment]
@pragmatrix I'm curious, how did you solve this problem with #1147 ? Doesn't the build in GitHub also need GN?

**Comment by tronical** [comment]
Ah yes, that explains it. Thanks. I guess that will break with https://github.com/actions/partner-runner-images/issues/85

**Comment by pragmatrix** [comment]
As a workaround, fetch-gn now falls back to downloading the amd64 binary in #1176. Closing.

**Comment by wszqkzqk** [comment]
> As a workaround, fetch-gn now falls back to downloading the amd64 binary in [#1176](https://github.com/rust-skia/rust-skia/pull/1176). Closing.

But this will result in the architecture that does not have gn binaries upstream not being able to use the system's gn, and it will be impossible to build from source
